### ISSUE TITLE
serde-diff panics on first diff msg upon ws reconnect

### ISSUE THREAD

**Issue by Boscop** [amethyst/serde-diff#16]
I'm sending diffs to my frontend via websockets, and I auto-reconnect to the backend because I'm often restarting it during development.
Normal msgs are received perfectly fine after the reconnect but serde-diff panics on the first diff msg it receives after a ws reconnect.
It seems to be happening in the deserializing code for `Option`:
```
output @ frontend.js:175
frontend.js:476 Uncaught RuntimeError: unreachable
    at __rust_start_panic (wasm-function[7100]:0x1fae53)
    at rust_panic (wasm-function[7094]:0x1fabb0)
    at _ZN3std9panicking20rust_panic_with_hook17hb92129b68ed9b10fE (wasm-function[7089]:0x1fa8d4)
    at _ZN3std9panicking11begin_panic17h742ec3e2a1b90089E (wasm-function[2101]:0xd142f)
    at _ZN71_$LT$core..option..Option$LT$T$GT$$u20$as$u20$serde_diff..SerdeDiff$GT$5apply17h1c3c59d79ddb2975E (wasm-function[637]:0x304c2)
    at _ZN64_$LT$$u5b$T$u3b$$u20$_$u5d$$u20$as$u20$serde_diff..SerdeDiff$GT$5apply17hde05dc65b8d09068E (wasm-function[636]:0x2f81b)
    at _ZN77_$LT$core_types..views..SessionBoardView$u20$as$u20$serde_diff..SerdeDiff$GT$5apply17hd9c10f0374c45c18E (wasm-function[2098]:0xcff1e)
    at _ZN65_$LT$serde_diff..Apply$LT$T$GT$$u20$as$u20$serde..de..Visitor$GT$9visit_seq17ha60d341d7bbe4841E (wasm-function[1171]:0x8c09c)
    at _ZN94_$LT$$RF$mut$u20$bincode..de..Deserializer$LT$R$C$O$GT$$u20$as$u20$serde..de..Deserializer$GT$17deserialize_tuple17he6c1b01e599ea424E (wasm-function[3041]:0x11ae57)
    at _ZN94_$LT$$RF$mut$u20$bincode..de..Deserializer$LT$R$C$O$GT$$u20$as$u20$serde..de..Deserializer$GT$15deserialize_seq17hcb00bbed63102822E (wasm-function[3040]:0x11adb4)

__cargo_web_snippet_dc2fd915bd92f9e9c6a3bd15174f1414eee3dbaf @ frontend.js:775
stdweb::webcore::initialization::initialize::{{closure}}
std::panicking::rust_panic_with_hook
std::panicking::begin_panic
<core::option::Option<T> as serde_diff::SerdeDiff>::apply
<[T; _] as serde_diff::SerdeDiff>::apply
<core_types::views::SessionBoardView as serde_diff::SerdeDiff>::apply
<serde_diff::Apply<T> as serde::de::Visitor>::visit_seq
<&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_tuple
<&mut bincode::de::Deserializer<R,O> as serde::de::Deserializer>::deserialize_seq
<serde_diff::Apply<T> as serde::de::DeserializeSeed>::deserialize
bincode::internal::deserialize_from_custom_seed
bincode::internal::deserialize_seed
<frontend::app::Model as yew::html::Component>::update
<yew::html::scope::UpdateComponent<COMP> as yew::scheduler::Runnable>::run
yew::scheduler::Scheduler::put_and_try_run
yew::html::scope::Scope<COMP>::update
yew::html::scope::Scope<COMP>::send_message
yew::html::ComponentLink<COMP>::callback::{{closure}}
yew::callback::Callback<IN>::emit
yew::services::websocket::WebSocketService::connect::{{closure}}
<F as stdweb::webcore::callfn::CallMut<(A12,)>>::call_mut

**Comment by Boscop** [comment]
@kabergstrom 
Now I ported my frontend to imgui, and it still happens there, but with a real stacktrace:
```
thread 'main' panicked at 'assertion failed: self.is_none()', <::std::macros::panic macros>:2:4
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libcore\fmt\mod.rs:1052

   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\io\mod.rs:1428
   5: std::sys_common::backtrace::_print
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\panicking.rs:204

   8: std::panicking::default_hook
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\panicking.rs:224

   9: std::panicking::rust_panic_with_hook
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\panicking.rs:470

  10: std::panicking::begin_panic<str*>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\panicking.rs:397
  11: serde_diff::{{impl}}::apply<core_types::views::SlotView,bincode::de::{{impl}}::deserialize_tuple::Access<bincode::de::read::SliceReader, bincode::config::WithOtherLimit<bincode::config::WithOtherEndian<bincode::config::WithOtherLimit<bincode::config::Defa
             at <::std::macros::panic macros>:2
  12: serde_diff::{{impl}}::apply<core::option::Option<core_types::views::SlotView>,bincode::de::{{impl}}::deserialize_tuple::Access<bincode::de::read::SliceReader, bincode::config::WithOtherLimit<bincode::config::WithOtherEndian<bincode::config::WithOtherLimit
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-diff-0.2.0\src\lib.rs:1056
  13: core_types::views::{{impl}}::apply<bincode::de::{{impl}}::deserialize_tuple::Access<bincode::de::read::SliceReader, bincode::config::WithOtherLimit<bincode::config::WithOtherEndian<bincode::config::WithOtherLimit<bincode::config::DefaultOptions, bincode::
             at D:\projects\core_types\src\views.rs:140
  14: serde_diff::{{impl}}::visit_seq<core_types::views::SessionBoardView,bincode::de::{{impl}}::deserialize_tuple::Access<bincode::de::read::SliceReader, bincode::config::WithOtherLimit<bincode::config::WithOtherEndian<bincode::config::WithOtherLimit<bincode::
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-diff-0.2.0\src\lib.rs:505
  15: bincode::de::{{impl}}::deserialize_tuple<bincode::de::read::SliceReader,bincode::config::WithOtherLimit<bincode::config::WithOtherEndian<bincode::config::WithOtherLimit<bincode::config::DefaultOptions, bincode::internal::Infinite>, byteorder::LittleEndian
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\bincode-1.2.1\src\de\mod.rs:271
  16: bincode::de::{{impl}}::deserialize_seq<bincode::de::read::SliceReader,bincode::config::WithOtherLimit<bincode::config::WithOtherEndian<bincode::config::WithOtherLimit<bincode::config::DefaultOptions, bincode::internal::Infinite>, byteorder::LittleEndian>,
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\bincode-1.2.1\src\de\mod.rs:295
  17: serde_diff::{{impl}}::deserialize<core_types::views::SessionBoardView,mut bincode::de::Deserializer<bincode::de::read::SliceReader, bincode::config::WithOtherLimit<bincode::config::WithOtherEndian<bincode::config::WithOtherLimit<bincode::config::DefaultOp
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-diff-0.2.0\src\lib.rs:490
  18: bincode::internal::deserialize_from_custom_seed<bincode::de::read::SliceReader,serde_diff::Apply<core_types::views::SessionBoardView>,bincode::config::WithOtherLimit<bincode::config::WithOtherEndian<bincode::config::WithOtherLimit<bincode::config::Default
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\bincode-1.2.1\src\internal.rs:115
  19: bincode::internal::deserialize_seed<serde_diff::Apply<core_types::views::SessionBoardView>,bincode::config::WithOtherEndian<bincode::config::WithOtherLimit<bincode::config::DefaultOptions, bincode::internal::Infinite>, byteorder::LittleEndian>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\bincode-1.2.1\src\internal.rs:143
  20: bincode::config::Config::deserialize_seed
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\bincode-1.2.1\src\config.rs:280
  21: gui::model::Model::update
             at .\src\model.rs:232
```

**Comment by Boscop** [comment]
I guess it's because after a reconnect, the server assumes that the frontend's state is `Default::default()` but it is not, so when applying the diff for an `Option`, it assumes it's `None`, but it's not.
Can we make this not fail?

**Comment by Boscop** [comment]
Yes, I confirmed that when I reset the frontend's instance of the state to `Default` upon reconnect, then it doesn't panic on the first applied diff after reconnect.

**Comment by kabergstrom** [comment]
Hey,

I'm not sure what the behaviour should be here. We can't construct a T for a `Some(T)` value if the diff only contains a part of the T - what would you want the behaviour to be?

**Comment by Boscop** [comment]
@kabergstrom I mean, it panics when the target state is `Some(x)` but the diff that is coming in was a diff constructed going from `None` to `Some(y)`.
But I agree that it makes sense that applying a diff only succeeds if the object that it is applied to equals the source of the diff.
Maybe it could return an error in the case if it fails, instead of panicking?
